version: "3"

services:
  client:
    platform: linux/x86_64
    image: ghcr.io/shumilovsergey/shadowsocks-client:latest
    container_name: shadowsocks
    command:
      ss-local -s ${SERVER_IP}
               -p ${SERVER_PORT}
               -m ${ENCRYPTION_METHOD}
               -k ${PASSWORD}
               -b 0.0.0.0
               -l ${LOCAL_PORT}
               -t 60
               --fast-open
    ports:
      - "${LOCAL_PORT}:${LOCAL_PORT}"
    restart: unless-stopped


